// Generated by CoffeeScript 1.6.3
(function() {
  exports.config = {
    discount: {
      numProviders: 300
    },
    erd: {
      restaurantNames: ["U Romka", "U Tomka", "U Grzesia", "U Fabiana", "U Maćka", "U Jakuba", "U Marzenny", "U Patrycji", "U Filipa", "U Michała", "U Gabriela", "U Szymona", "U Anieli"],
      hireDate: "2012-09-01",
      payments: ["", "", "", "", "", "", "", "", "MBank", "Alior Bank", "PKO", "Deutsche Bank", "Credit Agricole", "Kredyt Bank"],
      restaurant: {
        simStart: new Date('2006-10-24'),
        simEnd: new Date('2010-09-27'),
        openTime: [7, 9],
        closeTime: [19, 22],
        minCapacity: 22,
        maxCapacity: 82,
        avgOrderSize: 3,
        minWaitMinutes: 30,
        maxWaitMinutes: 60,
        initialSalesRatio: 0.56,
        swing: {
          lowLimit: 0.998,
          highLimit: 1.0035,
          addFuncion: function(day) {
            return 3 * (Math.sin(0.3 * day) + 0.3 * Math.sin(day * 1.446)) * Math.sin(day / 20) * Math.sin(day / 100);
          }
        },
        changes: [
          {
            when: new Date('2009-12-04'),
            category: /.*/,
            addition: -30,
            duration: 10
          }, {
            when: new Date('2010-01-04'),
            category: /.*/,
            addition: 30,
            duration: 5
          }, {
            when: new Date('2007-04-03'),
            category: /pizza/,
            addition: 38,
            duration: 18
          }
        ]
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=config.map
*/
