// Generated by CoffeeScript 1.6.3
(function() {
  var providers;

  providers = {
    discont: ['Grupon', 'EmBank', 'eSKaeM', 'EsKaEm'],
    service: [
      {
        "Restaurante": {
          "Alkohol po godzinach": ["alkohol"],
          "Wieczorem taniej": ["mięsne", "napoje", "desery", "sałatki"],
          "Weekendowa Pizza": ["pizza"]
        }
      }
    ]
  };

  /*
      PUBLIC EXPORT
  */


  exports.providers = providers;

}).call(this);

/*
//@ sourceMappingURL=Data.map
*/
