// Generated by CoffeeScript 1.6.3
(function() {
  var Utils, dateUtils, dostawcy, fs, genToken, libxmljs, print, xml;

  dateUtils = require('date-utils');

  Utils = require('./Utils.js');

  libxmljs = require('libxmljs');

  fs = require('fs');

  xml = libxmljs.parseXmlString(fs.readFileSync('./xmlSource.xml'));

  print = console.log;

  genToken = function() {
    var i, str, _i;
    str = "";
    for (i = _i = 1; _i <= 10; i = ++_i) {
      str += String.fromCharCode('A'.charAt(0) + Utils.random.integer(24));
    }
    return str;
  };

  dostawcy = {
    uslugi: [],
    znizki: []
  };

  exports.simulate = function(config, erd) {
    var from, k, kategorie, restaurante, restauranteId, to, zasieg, znizka, znizki, _i, _len;
    restaurante = xml.get('uslugi/firma[@nazwa="Restaurante"]');
    restauranteId = restaurante.attr('id').value();
    znizki = xml.find('znizki/firma/znizka[@firma="' + restauranteId + '"]');
    for (_i = 0, _len = znizki.length; _i < _len; _i++) {
      znizka = znizki[_i];
      from = znizka.get('oferowane').attr('od').value();
      to = znizka.get('oferowane').attr('do').value();
      zasieg = new RegExp(znizka.get('zasieg').text());
      kategorie = (function() {
        var _j, _len1, _ref, _results;
        _ref = erd.Kategoria;
        _results = [];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          k = _ref[_j];
          if (zasieg.test(k.nazwa)) {
            _results.push(k);
          }
        }
        return _results;
      })();
      console.log("from, to:", from, to, (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = kategorie.length; _j < _len1; _j++) {
          k = kategorie[_j];
          _results.push(k.nazwa);
        }
        return _results;
      })());
      console.log("genToken():", genToken());
    }
    console.log("restaurante:", restauranteId);
    return console.log("znizka:", znizki.length);
  };

}).call(this);

/*
//@ sourceMappingURL=DiscountsSimulator.map
*/
