// Generated by CoffeeScript 1.6.3
(function() {
  var charlatan, config, data, i, name, restaurants, utils, _i, _len, _ref;

  config = require("./config.json");

  data = require('./Data.js');

  utils = require('./Utils.js');

  charlatan = require('charlatan');

  charlatan.setLocale('pl');

  restaurants = [];

  _ref = config.erd.restaurantNames;
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    name = _ref[i];
    restaurants.push({
      id: i,
      nazwa: name,
      adres: "" + (charlatan.Address.streetAddress()) + ", " + (charlatan.Address.zipCode()) + " " + (charlatan.Address.city()),
      godzina_otwarcia: utils.random.integer(7, 9),
      godzina_zamkniecia: utils.random.integer(19, 22),
      liczba_miejsc: utils.random.integer(22, 82)
    });
  }

  console.log("restaurants:", restaurants);

}).call(this);

/*
//@ sourceMappingURL=Generator.map
*/
