// Generated by CoffeeScript 1.6.3
(function() {
  var config, data, i, utils, _i, _ref;

  config = require("./config.json");

  data = require('./Data.js');

  utils = require('./Utils.js');

  for (i = _i = 1, _ref = config.discount.numProviders; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
    console.log("utils.random.companyName():", utils.random.companyName());
  }

}).call(this);

/*
//@ sourceMappingURL=Generator.map
*/
