// Generated by CoffeeScript 1.6.3
(function() {
  var Danie, ERD, Kategoria, Kelner, Restauracja, Zamowienie, ZamowienieProdukt, charlatan, config, danie, danie_data, data, discountsSimulator, i, j, kategoria_data, kelner, key, name, numWaiters, presenter, restauracja, salesSimulator, utils, _i, _j, _len, _ref, _ref1, _ref2;

  config = require("./config.js");

  for (name in config.config) {
    config[name] = config.config[name];
  }

  data = require('./Data.js');

  utils = require('./Utils.js');

  charlatan = require('charlatan');

  charlatan.setLocale('pl');

  salesSimulator = require('./SalesSimulator.js');

  discountsSimulator = require('./DiscountsSimulator.js');

  Restauracja = [];

  Kelner = [];

  Kategoria = [];

  Danie = [];

  Zamowienie = [];

  ZamowienieProdukt = [];

  ERD = {
    Restauracja: Restauracja,
    Kelner: Kelner,
    Kategoria: Kategoria,
    Danie: Danie,
    Zamowienie: Zamowienie,
    ZamowienieProdukt: ZamowienieProdukt,
    id: function(entity) {
      return entity.length + 1;
    }
  };

  _ref = data.kategorie;
  for (key in _ref) {
    kategoria_data = _ref[key];
    kategoria_data.id = ERD.id(Kategoria);
    Kategoria.push(kategoria_data);
    kategoria_data.dania = [];
  }

  _ref1 = data.dania;
  for (key in _ref1) {
    danie_data = _ref1[key];
    danie = {
      id: ERD.id(Danie),
      nazwa: danie_data[0],
      cena: danie_data[1],
      porcja: danie_data[2],
      kategoria: danie_data[3]
    };
    danie.kategoria.dania.push(danie);
    Danie.push(danie);
    danie_data.id = danie.id;
  }

  _ref2 = config.erd.restaurantNames;
  for (i = _i = 0, _len = _ref2.length; _i < _len; i = ++_i) {
    name = _ref2[i];
    restauracja = {
      id: ERD.id(Restauracja),
      nazwa: name,
      adres: "" + (charlatan.Address.streetAddress()) + ", " + (charlatan.Address.zipCode()) + " " + (charlatan.Address.city()),
      godzina_otwarcia: utils.random.integer(config.erd.restaurant.openTime[0], config.erd.restaurant.openTime[1]),
      godzina_zamkniecia: utils.random.integer(config.erd.restaurant.closeTime[0], config.erd.restaurant.closeTime[1]),
      liczba_miejsc: utils.random.integer(config.erd.restaurant.minCapacity, config.erd.restaurant.maxCapacity),
      kelnerzy: []
    };
    Restauracja.push(restauracja);
    numWaiters = Math.ceil(Math.random() * 0.1 + 0.95 * restauracja.liczba_miejsc / 8);
    for (j = _j = 1; 1 <= numWaiters ? _j <= numWaiters : _j >= numWaiters; j = 1 <= numWaiters ? ++_j : --_j) {
      kelner = {
        id: ERD.id(Kelner),
        restauracja: restauracja,
        imie: charlatan.Name.firstName(),
        nazwisko: charlatan.Name.lastName(),
        data_zatrudnienia: config.erd.hireDate
      };
      Kelner.push(kelner);
      restauracja.kelnerzy.push(kelner);
    }
  }

  discountsSimulator.simulate(config, ERD);

  console.log("Zamowienie:", Zamowienie.length);

  console.log("ZamowienieProdukt:", ZamowienieProdukt.length);

  presenter = require('./Presenter.js');

  presenter.writeSQL(ERD);

}).call(this);

/*
//@ sourceMappingURL=Generator.map
*/
