// Generated by CoffeeScript 1.6.3
(function() {
  var NAME, fs, header, line, save, str;

  fs = require('fs');

  NAME = 'insert.sql';

  str = "";

  save = function() {
    if (fs.exists(NAME)) {
      fs.remove(NAME);
    }
    return fs.writeFile(NAME, str, function(err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log("The file was saved to " + NAME);
      }
    });
  };

  header = function(s) {
    var i, l, _i, _ref;
    l = "";
    for (i = _i = 1, _ref = s.length + 6; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      l += "-";
    }
    return "\n" + l + "\n-- " + s + " --\n" + l + "\n";
  };

  line = function(s) {
    return str += "" + s + "\n";
  };

  exports.writeSQL = function(erd) {
    var k, r, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
    line(header('RESTAURACJE'));
    _ref = erd.Restauracja;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      r = _ref[_i];
      line("INSERT INTO Restauracje VALUES (" + r.id + ", '" + r.nazwa + "', '" + r.adres + "', " + r.godzina_otwarcia + ", " + r.godzina_zamkniecia + ", " + r.liczba_miejsc + ");");
    }
    line(header('KELNERZY'));
    _ref1 = erd.Kelner;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      r = _ref1[_j];
      line("INSERT INTO Kelnerzy VALUES (" + r.id + ", '" + r.nazwisko + "', '" + r.imie + "', " + r.data_zatrudnienia + ", " + r.restauracja.id + ");");
    }
    line(header('KATEGORIE'));
    _ref2 = erd.Kategoria;
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      k = _ref2[_k];
      line("INSERT INTO KATEGORIE VALUES ('" + k.id + "', '" + k.nazwa + "', '" + k.opis + "');");
    }
    return save();
  };

}).call(this);

/*
//@ sourceMappingURL=Presenter.map
*/
