// Generated by CoffeeScript 1.6.3
(function() {
  var NAME, fs, line, save, str;

  fs = require('fs');

  NAME = 'insert.sql';

  str = "";

  save = function() {
    if (fs.exists(NAME)) {
      fs.remove(NAME);
    }
    return fs.writeFile(NAME, str, function(err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log("The file was saved to " + NAME);
      }
    });
  };

  line = function(s) {
    return str += "" + s + "\n";
  };

  exports.writeSQL = function(erd) {
    var r, _i, _len, _ref;
    _ref = erd.Restauracja;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      r = _ref[_i];
      line("INSERT INTO Restauracja VALUES (" + r.id + ", '" + r.nazwa + "', '" + r.adres + "', " + r.godzina_otwarcia + ", " + r.godzina_zamkniecia + ", " + r.liczba_miejsc + ")");
    }
    return save();
  };

}).call(this);

/*
//@ sourceMappingURL=Presenter.map
*/
