// Generated by CoffeeScript 1.6.3
(function() {
  var NAME, fs, header, line, save, str;

  fs = require('fs');

  NAME = 'insert.sql';

  str = "";

  save = function() {
    if (fs.exists(NAME)) {
      fs.remove(NAME);
    }
    return fs.writeFile(NAME, str, function(err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log("The file was saved to " + NAME);
      }
    });
  };

  header = function(s) {
    var i, l, _i, _ref;
    l = "";
    for (i = _i = 1, _ref = s.length + 6; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      l += "-";
    }
    return "\n" + l + "\n-- " + s + " --\n" + l + "\n";
  };

  line = function(s) {
    return str += "" + s + "\n";
  };

  exports.writeSQL = function(erd) {
    var d, k, k2, r, z, zp, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    line(header('RESTAURACJE'));
    _ref = erd.Restauracja;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      r = _ref[_i];
      line("INSERT INTO Restauracje VALUES (" + r.id + ", '" + r.nazwa + "', '" + r.adres + "', " + r.godzina_otwarcia + ", " + r.godzina_zamkniecia + ", " + r.liczba_miejsc + ")");
    }
    line(header('KELNERZY'));
    _ref1 = erd.Kelner;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      k = _ref1[_j];
      line("INSERT INTO Kelnerzy VALUES (" + k.id + ", " + k.restauracja.id + ", '" + k.nazwisko + "', '" + k.imie + "', '" + k.data_zatrudnienia + "')");
    }
    line(header('KATEGORIE'));
    _ref2 = erd.Kategoria;
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      k2 = _ref2[_k];
      line("INSERT INTO Kategorie VALUES (" + k2.id + ", '" + k2.nazwa + "', '" + k2.opis + "')");
    }
    line(header('DANIA'));
    _ref3 = erd.Danie;
    for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
      d = _ref3[_l];
      line("INSERT INTO Dania VALUES (" + d.id + ", " + d.kategoria.id + ", '" + d.nazwa + "', " + d.cena + ", " + d.porcja + ", '" + d.kategoria.jednostka + "')");
    }
    line(header('ZAMOWIENIA'));
    _ref4 = erd.Zamowienie;
    for (_m = 0, _len4 = _ref4.length; _m < _len4; _m++) {
      z = _ref4[_m];
      line("INSERT INTO Zamowienia VALUES (" + z.id + ", " + z.kelner.id + ", '" + z.data_przyjecia + "', '" + z.data_platnosci + "', " + z.numer_stolika + ", 'ABCDEFGHIJKLM', '" + z.platnosc + "')");
    }
    line(header('ZAMOWIENIA_DANIA'));
    _ref5 = erd.ZamowienieProdukt;
    for (_n = 0, _len5 = _ref5.length; _n < _len5; _n++) {
      zp = _ref5[_n];
      line("INSERT INTO ZamowieniaDania VALUES (" + zp.zamowienie.id + ", " + zp.danie.id + ", " + zp.porcja + ", " + zp.cena + ")");
    }
    return save();
  };

}).call(this);

/*
//@ sourceMappingURL=Presenter.map
*/
