// Generated by CoffeeScript 1.6.3
(function() {
  var key, names, randomParts, utils, value;

  names = [
    {
      food: ["Restaurante", "Pizzerina", "U Tobiasza", "Grzane odgrzewane", "McTusk", "Swojski zapach", "Klasyka smaku"],
      entertainment: ["3'Ball Center", "U7", "Centrum Handlowe Beta"],
      medical: ["SwissMet", "Germedica", "Altenpflege Pro"]
    }
  ];

  randomParts = "super pos hub muss hajo lobo hyper uber kalo new rich wed mon ptero tera giga mini gust serwis strefa zatoka kraina eden".split(" ");

  utils = {
    random: {
      integer: function(from, to) {
        if (to == null) {
          to = null;
        }
        if (from == null) {
          to = from;
          from = 0;
        }
        return Math.floor(Math.random() * (to - from) + from);
      },
      companyName: function(category) {
        var infix, prefixIndex, set, suffixIndex;
        if (category == null) {
          category = "food";
        }
        set = names[category];
        debugger;
        if (Math.random() < 0.10) {
          return set[utils.random(set.length)];
        }
        prefixIndex = utils.random.integer(randomParts.length);
        suffixIndex = utils.random.integer(randomParts.length - 1);
        if (suffixIndex >= prefixIndex) {
          suffixIndex++;
        }
        if (Math.random() < .2) {
          infix = " " + set[utils.random(set.length)] + " ";
        } else {
          "";
        }
        return "" + randomParts[prefixIndex] + infix + randomParts[suffixIndex];
      }
    }
  };

  for (key in utils) {
    value = utils[key];
    exports[key] = value;
  }

}).call(this);

/*
//@ sourceMappingURL=Utils.map
*/
