// Generated by CoffeeScript 1.6.3
(function() {
  var NAME, fs, save, str;

  fs = require('fs');

  NAME = 'discounts.xml';

  str = "";

  save = function() {
    if (fs.exists(NAME)) {
      fs.remove(NAME);
    }
    return fs.writeFile(NAME, str, function(err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log("The file was saved to " + NAME);
      }
    });
  };

  exports.writeXML = function(discounts) {
    return null;
  };

}).call(this);

/*
//@ sourceMappingURL=XMLPresenter.map
*/
